apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-submission-api
  namespace: default
  annotations:
    argocd-image-updater.argoproj.io/image-list: ghcr.io/durgesh191/kubernetes-cicd-tutorial
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/ghcr.io_durgesh191_kubernetes-cicd-tutorial.update-strategy: latest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grade-submission-api
  template:
    metadata:
      labels:
        app: grade-submission-api
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: grade-submission-api
        image: ghcr.io/durgesh191/kubernetes-cicd-tutorial:2399c681513334673816d461253ecd592e4a8eb6
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: grade-submission-api
  namespace: default
spec:
  type: NodePort
  selector:
    app: grade-submission-api
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
